server:
  port: 80

#  servlet:
#    context-path: /syning    # 应用路径上下文

spring:
  application:
    name: syning-blog
  mvc:
    static-path-pattern: /res/**


  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码
    charset: utf-8
    # 设置页面缓存
    cache: true


  profiles:
    active: dev



mybatis-plus:

  # 实体类别名
  type-aliases-package: com.syning.entity
  # 配置
  configuration:

    call-setters-on-nulls: false    # 如果查询语句中某些字段是null，就不会返回，false关闭

  mapper-locations: classpath:mapper/**/*.xml





logging:
  level:
    root: info
    com.syning.mapper: info


syning:
  power: true




