

# 云数据库
spring:
  datasource:

    url: jdbc:mysql://rm-bp12i1d596pb4fdg4ko.mysql.rds.aliyuncs.com:3306/syning_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: syning
    password: Shangyining0310


    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
